/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ErasureCode */

#ifndef _Included_ErasureCode
#define _Included_ErasureCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ErasureCode
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ErasureCode_print
  (JNIEnv *, jobject);

/*
 * Class:     ErasureCode
 * Method:    create_encode_decode_matrix
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ErasureCode_create_1encode_1decode_1matrix
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ErasureCode
 * Method:    destroy_encode_decode_matrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ErasureCode_destroy_1encode_1decode_1matrix
  (JNIEnv *, jobject);

/*
 * Class:     ErasureCode
 * Method:    cmain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ErasureCode_cmain
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
